version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      # Il est cinq heures, Paris s'éveille !
      time: "05:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "ci:"
  # Update root go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "go:"
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
      k8s:
        patterns:
          - "k8s.io/*"
      docker:
        patterns:
          - "github.com/docker/*"
          - "github.com/moby/*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"
  # Update other go depedendencies
  - package-ecosystem: "gomod"
    directory: "/examples/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "go:"
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
      k8s:
        patterns:
          - "k8s.io/*"
      docker:
        patterns:
          - "github.com/docker/docker/*"
          - "github.com/moby/moby/*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"
  - package-ecosystem: "gomod"
    directory: "/tools/eks-cleanup/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "go:"
  - package-ecosystem: "gomod"
    directory: "/tools/testjson2md/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "go:"
  - package-ecosystem: "gomod"
    directory: "/tools/dnstester/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "go:"
  - package-ecosystem: "docker"
    directory: "/Dockerfiles"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "Dockerfiles:"
